booking/urls.py
from django.conf.urls import url
from django.contrib import admin
from hotels.views import MainView, HotelDetailView
from django.conf import settings
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', MainView.as_view(), name="main_view"),
    url(r'^search/', MainView.as_view(), name="search_view"),
    url(r'^hotel/(?P<pk>\d+)/$', HotelDetailView.as_view(), name="hotel_view"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

hotels/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Hotel(models.Model):
    CLASSES_CHOICES = (("First", "1"), ("Second", "2"), ("Thrid", "3"), ("Fourth", "4"), ("Fifth", "5"))
    name = models.CharField(max_length=100)
    location = models.CharField(max_length= 50)
    standard = models.CharField(max_length=1,choices=CLASSES_CHOICES)

class Room(models.Model):
    hotel_id = models.ForeignKey("Hotel", on_delete=models.CASCADE)
    number_persons = models.IntegerField()
    prize = models.DecimalField(max_digits=6, decimal_places=2)

hotels/forms.py
from django.forms import ModelForm
from .models import Hotel


class HotelForm(ModelForm):
    class Meta:
        model = Hotel
        fields = ['location', 'standard']

    def __init__(self, *args, **kwargs):
        super(HotelForm, self).__init__(*args, **kwargs)
        self.fields['location'].required = False
        self.fields['standard'].required = False

hotels/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormMixin
from .models import Hotel
from .forms import HotelForm
from django.db.models import Min, Max
from django.db.models import QuerySet
from django.shortcuts import render

# Create your views here.

class MainView(ListView, FormMixin):
    model = Hotel
    template_name = "index.html"
    form_class = HotelForm

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        is_location = request.GET.get('location', False)
        is_standard = request.GET.get('standard', False)
        if is_location:
            city = request.GET['location']
            objects = Hotel.objects.filter(location=city)
        elif is_standard:
            standard = request.GET['standard']
            if objects:
                objects = objects.filter(standard=dict(Hotel.CLASSES_CHOICES)[standard])
            else:
                objects = Hotel.objects.filter(standard=dict(Hotel.CLASSES_CHOICES)[standard])
        else:
            objects = Hotel.objects.all()
        self.object_list = objects
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(MainView, self).get_context_data(**kwargs)
        hotels = context['object_list']
        hotels = hotels.annotate(min_prize = Min('room__prize'))
        hotels = hotels.annotate(max_prize = Max('room__prize'))
        context['object_list'] = hotels
        return context

class HotelDetailView(DetailView):
    model = Hotel
    template_name = "hotel_detail.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        return context

hotels/templates/hotel_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Welcome in hotel {{ object.name }}.</p>
<p>In {{ object.location }}</p>
{% for room in object.room_set.all %}
    <div style="border:1px solid black; padding: 10px">
        <p>There is a room for {{ room.number_persons }} persons.</p>
        <p>The price is {{ room.prize }} dollars.</p>
    </div>
{% endfor %}
</body>
</html>

hotels/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="content" style="display: flex">
        <div style="flex: 30%">
        Search hotel form
        <form method="get" action={% url 'search_view' %}>
            {{ form }}
            <p><input type="submit" value="Search"></p>
        </form>
        </div>
        <div style="flex: 40%">
        {% for object in object_list %}
            <div style="border:1px solid black; padding: 10px">
                <p><a href="{% url 'hotel_view' pk=object.pk %}">{{ object.name }}</a></p>
            <p>{{ object.location }}</p>
            <p>{{ object.standard }}</p>
            <p>Price: from {{ object.min_prize }} to {{ object.max_prize }}</p>
            </div>
        {% endfor %}
        </div>
    </div>
</body>
</html>